include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_web_libraries_in_flutter
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
