name: breathing_app
description: Real-time breath phase classification application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^11.4.0
  provider: ^6.1.1
  flutter_sound: ^9.2.13
  path_provider: ^2.1.2
  flutter_animate: ^4.5.0
  record: ^5.2.1
  audio_device_info_windows:
    path: ./plugins/audio_device_info_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/
    - assets/fonts/
    - assets/models/breath_classifier_model_mel_input.onnx
    # - assets/models/breath_classifier_model_audio_input.onnx.data
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
