name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint with Pylint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Pylint only
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint without project deps
        run: |
          files=$(git ls-files '*.py')
          if [ -z "$files" ]; then
            echo "No Python files to lint"
            exit 0
          fi
          pylint "$files" --disable=E0401,C0116,C0114,C0115,C0116
